
services:
  veldhub_db:
    extends:
      file: ./modules/veld_registry/compose.yaml
      service: veldhub_db
    networks:
      - veldhub_backend_network

  veldhub_backend_with_db:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./modules:/modules
    environment:
      DB_HOST: $DB_HOST
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    networks:
      - veldhub_backend_network
    depends_on:
      veldhub_db:
        condition: service_started

  veldhub_backend_no_db:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./modules:/modules

networks:
  veldhub_backend_network:
