
services:
  veldhub_db:
    extends:
      file: ./src/veld_registry/compose.yaml
      service: veldhub_db
    networks:
      - veldhub_backend_network

  veldhub_backend_src_with_db:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src
    command: python /src/main.py
    networks:
      - veldhub_backend_network
    depends_on:
      veldhub_db:
        condition: service_started

  veldhub_backend_src:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src

networks:
  veldhub_backend_network:
