
services:
  veldhub_db:
    build: 
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ../data/db:/var/lib/postgresql/data
    networks:
      - veldhub_backend_network

  veldhub_backend:
    build: 
      dockerfile: ./backend.dockerfile
    volumes:
      - ../src:/src
    depends_on:
      veldhub_db:
        condition: service_started
    networks:
      - veldhub_backend_network

networks:
  veldhub_backend_network:
