
services:
  veldhub_db:
    extends:
      file: ../src/veld_registry/docker/compose.yaml
      service: veldhub_db
    networks:
      - veldhub_backend_network

  veldhub_backend:
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ../src:/src
    command: python /src/main.py
    networks:
      - veldhub_backend_network
    depends_on:
      veldhub_db:
        condition: service_started

networks:
  veldhub_backend_network:
