services:
  veldhub_db:
    build: 
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data
      - ./sql_init_scripts/:/docker-entrypoint-initdb.d/
