services:
  veldhub_db:
    build: 
      dockerfile: ./Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data/db
